### ISSUE TITLE
Petición de curso de osciloscopi

### ISSUE THREAD

**Issue by Jesus2354** [cansi22/Curso-Soldadura#1]
Buenas!!, me gustaría un cursillo para manejar el oscilospio debido a que mi profesor no tiene ni idea, Gracias!!

**Comment by cansi22** [comment]
Soy un antiguo alumno que hizo este curso que se hizo hace 6 años.
Si quieres hacer algo proponlo en la Asociación de Electrónica, creo que sigue opertiva.
